#!/bin/bash

# QUICK SETUP GUIDE FOR ADMIN PANEL DEPLOYMENT
# admin.thegreatbulls.in on Vercel with GitHub Actions

echo "============================================"
echo "Admin Panel Deployment Setup"
echo "admin.thegreatbulls.in"
echo "============================================"
echo ""

echo "📋 STEP 1: Get Vercel Credentials"
echo "=================================="
echo ""
echo "1. Go to: https://vercel.com/account/tokens"
echo "2. Create a new Personal Access Token"
echo "3. Copy the token - you'll need it"
echo ""
read -p "Press Enter after copying your VERCEL_TOKEN..."
echo ""

echo "4. Go to your Vercel Dashboard"
echo "5. Select your project 'thegreatbulls'"
echo "6. Settings → General"
echo "7. Copy:"
echo "   - Project ID"
echo "   - Team/Org ID"
echo ""
read -p "Press Enter after copying Project ID and Org ID..."
echo ""

echo "📝 STEP 2: Add GitHub Secrets"
echo "============================="
echo ""
echo "1. Go to: GitHub Repository"
echo "2. Settings → Secrets and variables → Actions"
echo "3. Click 'New repository secret'"
echo ""
echo "Add these 3 secrets:"
echo "  - Name: VERCEL_TOKEN"
echo "    Value: <your-token>"
echo "  - Name: VERCEL_ORG_ID"
echo "    Value: <your-org-id>"
echo "  - Name: VERCEL_PROJECT_ID"
echo "    Value: <your-project-id>"
echo ""
read -p "Press Enter after adding secrets..."
echo ""

echo "🌐 STEP 3: Configure DNS in GoDaddy"
echo "===================================="
echo ""
echo "1. Go to GoDaddy Domain Management"
echo "2. Click 'DNS' for thegreatbulls.in"
echo "3. Add a new CNAME record:"
echo "   - Type: CNAME"
echo "   - Name: admin"
echo "   - Value: cname.vercel-dns.com"
echo "   - TTL: 3600"
echo ""
echo "4. Save and wait 24-48 hours for DNS propagation"
echo ""
read -p "Press Enter after configuring DNS..."
echo ""

echo "✅ STEP 4: Test Deployment"
echo "========================="
echo ""
echo "Make a test change:"
echo "  1. Edit lib/admin_panel.dart"
echo "  2. Commit: git add . && git commit -m 'Test deployment'"
echo "  3. Push: git push origin main"
echo "  4. Go to GitHub → Actions"
echo "  5. Watch the build happen automatically!"
echo ""

echo "🚀 STEP 5: Access Live Admin Panel"
echo "=================================="
echo ""
echo "Once DNS propagates (24-48 hours):"
echo "  https://admin.thegreatbulls.in"
echo ""

echo "⚡ LIVE EDITING WORKFLOW"
echo "======================="
echo ""
echo "Development (Local):"
echo "  1. flutter run -d chrome"
echo "  2. Make changes"
echo "  3. Press 'r' to hot reload"
echo ""
echo "Production (Live):"
echo "  1. Make changes to admin_panel.dart"
echo "  2. git add . && git commit -m 'Your message'"
echo "  3. git push origin main"
echo "  4. GitHub Actions auto-deploys (2-5 min)"
echo "  5. admin.thegreatbulls.in updated! ✨"
echo ""

echo "📊 MONITORING"
echo "============="
echo "  - Vercel: https://vercel.com/dashboard"
echo "  - GitHub Actions: https://github.com/<user>/<repo>/actions"
echo "  - Check deployment: https://admin.thegreatbulls.in"
echo ""

echo "✨ Setup Complete! ✨"
echo ""
echo "Next: Add your secrets to GitHub and test!"
